receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  # prometheus:
  #   config:
  #     scrape_configs:
  #     - job_name: 'otel-collector'
  #       scrape_interval: 10s
  #       static_configs:
  #       - targets: ['0.0.0.0:8888']
  #     - job_name: 'node'
  #       scrape_interval: 10s
  #       static_configs:
  #       - targets: ['localhost:9100']

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    external_labels:
      env: local
    # tls:
    #   insecure: true
    # remote_write_queue:
    #   enabled: false
    #   num_consumers: 10
  # prometheus:
  #   endpoint: 0.0.0.0:1234
    # retry_on_failure:
    #   enabled: true
    #   initial_interval: 5s
    #   max_interval: 10s
    #   max_elabsed_time: 30s
    # timeout: 15s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
      